Don't assume all test passed if cancelled (#599)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -792,6 +792,6 @@ jobs:
     steps:
       - name: All tests passed
         run: |
-          echo "All jobs passed: ${{ !contains(needs.*.result, 'failure') }}"
+          echo "All jobs passed: ${{ !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}"
           # shellcheck disable=SC2242
-          exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
+          exit ${{ (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && 1 || 0 }}
